# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180306_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='active',
        ),
    ]
