# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postmodel_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[('private', 'Private'), ('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=120),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Post Title'),
        ),
    ]
