# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180306_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[('private', 'Private'), ('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=120),
        ),
    ]
