# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180306_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[('private', 'Private'), ('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=120),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='Post Title'),
        ),
    ]
