# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180306_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(choices=[('private', 'Private'), ('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=120),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'blank': 'This field is required!', 'unique': 'This title is not unique,please try again?'}, help_text='Must be a unique title.', max_length=240, unique=True, verbose_name='Post Title'),
        ),
    ]
